project:
  type: book

book:
  title: "engine-mwe"
  author: "Norah Jones"
  date: "8/5/2024"
  chapters:
    - index.qmd
    - index2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



